### ISSUE TITLE
How to compile

### ISSUE THREAD

**Issue by sirpete83** [EmmanuelP/yawsnd#2]
Dear Emmanuel,
I'm not familiar with the meson build. It runs on Linux? I have an Ubuntu machine here, so it might work?
Perhaps you can provide the required dependencies. And how to run the build process.
Many thanks. Peter

**Comment by EmmanuelP** [comment]
Hi Peter,

I'm not sure sure how useful this library will be for you, I had the project of recording the soundmeter data over a long period, but this project is on hold for now.

Anyway, if you want to test it, ubuntu is fine.

You will need meson, ninja, glib and mosquitto development packages. Once the packages are installed, building the project is a matter of a few commands, from the source code top repository:

```
meson build
cd build
ninja
```

Have a look at the meson documentation: https://mesonbuild.com/Quick-guide.html#compiling-a-meson-project

**Comment by sirpete83** [comment]
at this moment I found the workflows folder, think I can extract the needed inforamtions. And Thanks for your reply.
I will try it tomorrow.
